import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import TechCard from "../components/TechCards";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pierre N. Smith | Kipp0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="flex flex-col min-h-screen">
        <div className="flex flex-col h-full items-center justify-center flex-1">

          <h1 className="text-6xl md:text-[6rem] leading-normal font-extrabold text-gray-700">
            Pierre N. Smith
          </h1>
          <h2 className="text-2xl md:text-[2rem] leading-normal">SOFTWARE ENGINEER, FOUNDER, & AMATEUR MUSICIAN</h2>
        </div>
      </Header>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">

        <p className="text-2xl text-gray-700">My Bread and Butter:</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-3 lg:w-2/3">
          <TechCard
            name="NextJS"
            description=""
            documentation="https://nextjs.org/"
          />

          <TechCard name="TypeScript"
            description="Started using typescript during a "
            documentation="Since 2020"
          />
          <TechCard
            name="TailwindCSS"
            description="Rapidly build modern websites without ever leaving your HTML"
            documentation="https://tailwindcss.com/"
          />
          <TechCard
            name="tRPC"
            description="End-to-end typesafe APIs made easy"
            documentation="https://trpc.io/"
          />
          <TechCard
            name="Next-Auth"
            description="Authentication for Next.js"
            documentation="https://next-auth.js.org/"
          />
          <TechCard
            name="Prisma"
            description="Build data-driven JavaScript & TypeScript apps in less time"
            documentation="https://www.prisma.io/docs/"
          />
        </div>
      </main>
    </>
  );
};

export default Home;

